第4回課題
Yumu0112/AWS-demo pull request #3
Opened 2023-07-18 09:03 UTC by Yumu0112

2023-07-18 11:18 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！

2023-07-18 11:18 UTC, MasatoshiMizumoto commented on .DS_Store
このファイルは含まれないようにしてください！

2023-07-18 11:18 UTC, MasatoshiMizumoto commented on image04/.DS_Store
このファイルも含まれないようにお願いします！

2023-07-19 00:33 UTC, Yumu0112 commented on image04/.DS_Store
396ecf24a4f756976a3f86995b15ef3f0e4bd41e

修正しました

2023-07-19 00:46 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！

2023-07-19 00:46 UTC, MasatoshiMizumoto commented on .gitignore
改行なしの警告出てますので出ないようにお願いします！

2023-07-19 00:46 UTC, MasatoshiMizumoto commented on image04/ec2-info.png
これは作成したVPCじゃないですね！

2023-07-19 00:56 UTC, Yumu0112 commented on image04/ec2-info.png
e9dd27aac1422102ab05fafcf2730f127498d5e0

すみません、画像が間違えていました。
下記にて接続を行なっています。

2023-07-19 01:00 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-07-19 01:07 UTC, merged